/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Testdll */

#ifndef _Included_Testdll
#define _Included_Testdll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Testdll
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Testdll_get
  (JNIEnv *, jclass);

/*
 * Class:     Testdll
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Testdll_set
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
